- name: Amazon extras enable MariaDB
  shell: amazon-linux-extras enable lamp-mariadb10.2-php7.2

- name: Install required software
  package:
    name: "{{ software }}"
    state: present

- name: Get Docker registry IP from TF
  shell: "aws s3 cp s3://alacademyjenkins/env:/{{tfenv}}/{{ tfenv }}/terraform.tfstate - | jq -r '.outputs.docker_registry_ip.value'"
  register: registry_output

- name: Set docker reg ip
  set_fact:
    registry_ip: "{{registry_output.stdout}}"

- name: DEBUG
  debug:
    msg:
      - "CMD: {{ registry_output }}"
      - "ENVIRONMENT: {{ tfenv}} "
      - "STDOUT: {{registry_ip}} "

- name: Set the insecure registry
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: Start docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Add Jenkins and ec2-user to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - jenkins
    - ec2-user
