- name: Create a jenkins job using basic authentication
  jenkins_job:
    config: "{{ lookup('file', '{{role_path}}/files/{{item}}') }}"
    name: "{{ item }}"
    password: "{{ adminpw }}"
    url: http://localhost:8080
    user: admin
  with_items: "{{ jenkins_jobs }}"
