- name: Create a jenkins job using basic authentication
  jenkins_job:
    config: "{{ item }}"
    name: "{{ item }}"
    password: "{{ adminpw }}"
    url: http://localhost:8080
    user: admin
  with_items: "{{ jenkins_jobs }}"
